"""empty message

Revision ID: 0352f1997623
Revises: e2d81d897345
Create Date: 2024-10-09 10:44:13.700609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0352f1997623'
down_revision = 'e2d81d897345'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dl_ms_category',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True, comment='Nama Category'),
    sa.Column('rigid_or_flexy', sa.Boolean(), nullable=True, comment='Rigid or Flexy'),
    sa.Column('edges_a', sa.Integer(), nullable=True, comment='Edges A'),
    sa.Column('edges_b', sa.Integer(), nullable=True, comment='Edges B'),
    sa.Column('edges_c', sa.Integer(), nullable=True, comment='Edges C'),
    sa.Column('edges_d', sa.Integer(), nullable=True, comment='Edges D'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dl_ms_features',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Nama Equipment Tree'),
    sa.Column('category', sa.String(length=255), nullable=False, comment='Nama Category'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dl_features_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('equipment_id', sa.UUID(), nullable=True, comment='ref to id table ini sendiri (recursive)'),
    sa.Column('features_id', sa.UUID(), nullable=True),
    sa.Column('date_time', sa.DateTime(), nullable=True, comment='Date Time'),
    sa.Column('value', sa.Float(), nullable=True, comment='Value'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment_master.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['features_id'], ['dl_ms_features.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dl_predict',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('equipment_id', sa.UUID(), nullable=True, comment='ref to id table ini sendiri (recursive)'),
    sa.Column('features_id', sa.UUID(), nullable=True),
    sa.Column('pfi_value', sa.Float(), nullable=True, comment='Value'),
    sa.Column('status', sa.String(length=255), nullable=True, comment='Status'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment_master.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['features_id'], ['dl_ms_features.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('equipment_master', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.UUID(), nullable=True))
        batch_op.alter_column('equipment_tree_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='ref to id table ini sendiri (recursive)',
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'dl_ms_category', ['category_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment_master', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('equipment_tree_id',
               existing_type=sa.UUID(),
               comment='ref to id table ini sendiri (recursive)',
               existing_nullable=True)
        batch_op.drop_column('category_id')

    op.drop_table('dl_predict')
    op.drop_table('dl_features_data')
    op.drop_table('dl_ms_features')
    op.drop_table('dl_ms_category')
    # ### end Alembic commands ###
