"""empty message

Revision ID: 10456ec8e4e3
Revises: 98f8eb30f594
Create Date: 2024-10-04 16:59:35.558569

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '10456ec8e4e3'
down_revision = '98f8eb30f594'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hl_tr_data_detail_root_cause_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('root_cause_id', sa.UUID(), nullable=True, comment='Ref to hl_m_cause 1 to many'),
    sa.Column('cause_id', sa.UUID(), nullable=True, comment='Ref to hl_m_cause 1 to many'),
    sa.Column('is_parent', sa.Boolean(), nullable=True, comment='1=ya, 0=tidak'),
    sa.Column('is_checked', sa.Boolean(), nullable=True, comment='1=ya, 0=tidak'),
    sa.Column('biaya', sa.Float(), nullable=True, comment='Besar Biaya yang dikeluarkan (input)'),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cause_id'], ['hl_ms_excel_variables_cause.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['root_cause_id'], ['hl_ms_excel_variables_cause.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hl_tr_data_detail_root_cause', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_cause_id', sa.UUID(), nullable=True, comment='Ref to hl_m_cause 1 to many'))
        batch_op.drop_constraint('hl_tr_data_detail_root_cause_cause_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'hl_ms_excel_variables_cause', ['parent_cause_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('cause_id')
        batch_op.drop_column('is_checked')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hl_tr_data_detail_root_cause', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_checked', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='1=ya, 0=tidak'))
        batch_op.add_column(sa.Column('cause_id', sa.UUID(), autoincrement=False, nullable=True, comment='Ref to hl_m_cause 1 to many'))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('hl_tr_data_detail_root_cause_cause_id_fkey', 'hl_ms_excel_variables_cause', ['cause_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('parent_cause_id')

    op.create_table('pfi_ms_tag',
    sa.Column('id', sa.BIGINT(), server_default=sa.text("nextval('pfi_ms_tag_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('web_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('path', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('descriptor', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('point_class', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('point_type', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('digital_set_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('engineering_units', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('span', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('zero', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('step', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('future', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('display_digits', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pfi_ms_tag_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('pfi_value_tag',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('tag_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('time_stamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('units_abbreviation', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('good', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('questionable', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('substituted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('annotated', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['pfi_ms_tag.id'], name='pfi_value_tag_tag_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pfi_value_tag_pkey')
    )
    op.create_table('pfi_ms_equipment',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('parent_id', sa.UUID(), autoincrement=False, nullable=True, comment='ref to id table ini sendiri (recursive)'),
    sa.Column('category_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='Nama Equipment'),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True, comment='Deskripsi Equipment'),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['pfi_ms_category.id'], name='pfi_ms_equipment_category_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['pfi_ms_equipment.id'], name='pfi_ms_equipment_parent_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pfi_ms_equipment_pkey')
    )
    op.create_table('pfi_ms_category',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='Nama Category'),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pfi_ms_category_pkey')
    )
    op.drop_table('hl_tr_data_detail_root_cause_members')
    # ### end Alembic commands ###
