"""empty message

Revision ID: 18bb27cfab28
Revises: 75a51adfe70b
Create Date: 2024-10-03 10:15:13.196732

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '18bb27cfab28'
down_revision = '75a51adfe70b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hl_ms_excel_variables', schema=None) as batch_op:
        batch_op.add_column(sa.Column('formula', sa.String(length=255), nullable=True, comment='Formula name for calculation'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hl_ms_excel_variables', schema=None) as batch_op:
        batch_op.drop_column('formula')

    # ### end Alembic commands ###
