"""empty message

Revision ID: 434585cfdaa3
Revises: 0352f1997623
Create Date: 2024-10-09 13:39:54.168022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '434585cfdaa3'
down_revision = '0352f1997623'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rm_master_likelihood',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True, comment='master data likelihood name'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rm_master_severity',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True, comment='master data severity name'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rm_risk_classification',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('risk_class', sa.String(length=100), nullable=True, comment='class'),
    sa.Column('likelihood_id', sa.UUID(), nullable=True),
    sa.Column('severity_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['likelihood_id'], ['rm_master_likelihood.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['severity_id'], ['rm_master_severity.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rm_pof_predict',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True, comment='pof predict year'),
    sa.Column('value', sa.Double(), nullable=True, comment='pof predict value'),
    sa.Column('eq_id', sa.UUID(), nullable=True),
    sa.Column('risk_class_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['eq_id'], ['equipment_master.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['risk_class_id'], ['rm_risk_classification.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rm_pof_predict')
    op.drop_table('rm_risk_classification')
    op.drop_table('rm_master_severity')
    op.drop_table('rm_master_likelihood')
    # ### end Alembic commands ###
