"""empty message

Revision ID: 96afaa765ef2
Revises: 21a0e64a898c
Create Date: 2024-10-28 14:25:37.728766

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '96afaa765ef2'
down_revision = '21a0e64a898c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hl_tr_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('periodic_end_date', sa.DateTime(), nullable=True))
        batch_op.alter_column('periode',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('rm_pof_predict', schema=None) as batch_op:
        batch_op.alter_column('eq_id',
               existing_type=sa.UUID(),
               comment='',
               existing_nullable=True)
        batch_op.alter_column('risk_class_id',
               existing_type=sa.UUID(),
               comment='',
               existing_nullable=True)

    with op.batch_alter_table('rm_risk_classification', schema=None) as batch_op:
        batch_op.alter_column('likelihood_id',
               existing_type=sa.UUID(),
               comment='',
               existing_nullable=True)
        batch_op.alter_column('severity_id',
               existing_type=sa.UUID(),
               comment='',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rm_risk_classification', schema=None) as batch_op:
        batch_op.alter_column('severity_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='',
               existing_nullable=True)
        batch_op.alter_column('likelihood_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='',
               existing_nullable=True)

    with op.batch_alter_table('rm_pof_predict', schema=None) as batch_op:
        batch_op.alter_column('risk_class_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='',
               existing_nullable=True)
        batch_op.alter_column('eq_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='',
               existing_nullable=True)

    with op.batch_alter_table('hl_tr_data_detail', schema=None) as batch_op:
        batch_op.create_index('hl_tr_data_detail_efficiency_transaction_id_idx', ['efficiency_transaction_id', 'variable_id'], unique=True)

    with op.batch_alter_table('hl_tr_data', schema=None) as batch_op:
        batch_op.create_index('hl_tr_data_name_idx', ['name'], unique=False)
        batch_op.alter_column('periode',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.drop_column('periodic_end_date')

    with op.batch_alter_table('hl_ms_excel_variables_cause', schema=None) as batch_op:
        batch_op.create_index('hl_ms_excel_variables_cause_id_idx', ['id', 'parent_id', 'variable_id'], unique=True)

    with op.batch_alter_table('hl_ms_excel_variables', schema=None) as batch_op:
        batch_op.create_index('hl_ms_excel_variables_excel_variable_name_idx', ['excel_variable_name', 'in_out', 'excel_id'], unique=True)

    # ### end Alembic commands ###
