"""empty message

Revision ID: b3d2ff2d7d18
Revises: 93b69fa3835e
Create Date: 2024-10-13 13:15:34.574093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3d2ff2d7d18'
down_revision = '93b69fa3835e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hl_ms_masterdata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nphr_value', sa.Float(), nullable=True))

    with op.batch_alter_table('hl_tr_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost_threshold', sa.Integer(), nullable=True))

    with op.batch_alter_table('rm_pof_predict', schema=None) as batch_op:
        batch_op.alter_column('eq_id',
               existing_type=sa.UUID(),
               comment='',
               existing_nullable=True)
        batch_op.alter_column('risk_class_id',
               existing_type=sa.UUID(),
               comment='',
               existing_nullable=True)

    with op.batch_alter_table('rm_risk_classification', schema=None) as batch_op:
        batch_op.alter_column('likelihood_id',
               existing_type=sa.UUID(),
               comment='',
               existing_nullable=True)
        batch_op.alter_column('severity_id',
               existing_type=sa.UUID(),
               comment='',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rm_risk_classification', schema=None) as batch_op:
        batch_op.alter_column('severity_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='',
               existing_nullable=True)
        batch_op.alter_column('likelihood_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='',
               existing_nullable=True)

    with op.batch_alter_table('rm_pof_predict', schema=None) as batch_op:
        batch_op.alter_column('risk_class_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='',
               existing_nullable=True)
        batch_op.alter_column('eq_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='',
               existing_nullable=True)

    with op.batch_alter_table('hl_tr_data', schema=None) as batch_op:
        batch_op.drop_column('cost_threshold')

    with op.batch_alter_table('hl_ms_masterdata', schema=None) as batch_op:
        batch_op.drop_column('nphr_value')

    # ### end Alembic commands ###
